{{/*
=============================================================================
ServiceAccount — used for SAT auth with AIO MQTT broker
=============================================================================
*/}}
{{- if .Values.mqtt.satAuth.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aio-sensor-intelligence.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "aio-sensor-intelligence.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: aio-sensor-intelligence
    helm.sh/chart: {{ include "aio-sensor-intelligence.chart" . }}
{{- end }}
